### ISSUE TITLE
Move descriptions to the HTML

### ISSUE THREAD

**Issue by workergnome** [SciutoAlex/p5d3-connect#4]
Right now, there's great descriptive text in the code comments for each of these projects.

I wonder if it would be worth moving that into a HTML block, maybe under the code, so that people looking at the examples could see it without viewing source?

**Comment by SciutoAlex** [comment]
What do you think of these pages?

http://sciutoalex.github.io/p5-D3-cookbook/
http://sciutoalex.github.io/p5-D3-cookbook/recipes-beginner/line-generators/
http://sciutoalex.github.io/p5-D3-cookbook/recipes-beginner/scales/
http://sciutoalex.github.io/p5-D3-cookbook/recipes-beginner/voronoi/

**Comment by SciutoAlex** [comment]
Closing. Refer to #3
