### ISSUE TITLE
Discuss:  Should these be single-file?

### ISSUE THREAD

**Issue by workergnome** [SciutoAlex/p5d3-connect#6]
I don't have a strong preference here, but it _might_ be nice to have these examples match the p5.js style of an `index.html` file and a `sketch.js` file?

It is nice to have single, well-named files as well, though, so...just a suggestion.

**Comment by SciutoAlex** [comment]
Based on #3, I think it's cleaner to split them into index.html and sketch.js. Having both description, example code, and actual code in the same html file is too messy.
